src/lib/Cachette.ts, test/Cachette_test.ts
Instead of taking an unbound function, getOrFetchValue() now expects the caller to bind the function.
Tests performed
---
* Adjusted unit tests
=> Take bound functions

package.json, src/lib/CacheClient.ts, test/CacheClient_test.ts
This removes the need to craft the cache key from the client side.
=> Clearing cached function call

package.json
To be usable, the TS typing file must be present in package.json
=> Publish typings in package.json

src/lib/CacheInstance.ts, src/lib/LocalCache.ts, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts, test/WriteThroughCache_test.ts
When the local cache was refreshed from a redis value, it always set the hardcoded value of 120s as the TTL.
=> WriteThroughCache: Fix TTL when local cache is refreshed

src/lib/LocalCache.ts, test/LocalCache_test.ts
This adds a default `maxAge` to the local cache, and maps some options to environment variables, so that we can experiment easily.
=> ⚙️ Adding max age setting for local cache

src/lib/CacheInstance.ts, src/lib/LocalCache.ts, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts
I feel like this should be part of the abstraction too, considered that clearing all of the items in the redis cache seems radical
=> allow clearing only in-memory items.

src/lib/CacheInstance.ts, src/lib/LocalCache.ts, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts, test/LocalCache_test.ts, test/RedisCache_test.ts, test/WriteThroughCache_test.ts
This is to troubleshoot the memory usage of the local cache, before and after clearing the memory it uses.
=> Add itemCount to Cache abstraction

package.json, test/mocha.ci.opts, test/mocha.opts
Cannot override options in mocha.opts, https://github.com/mochajs/mocha/issues/1444
- https://github.com/unitoio/babylon-client/pull/47
- https://github.com/unitoio/backoff-decorator/pull/17
- https://github.com/unitoio/cachette/pull/32
- https://github.com/unitoio/connectors/pull/2588
- https://github.com/unitoio/keuf/pull/8
- https://github.com/unitoio/scheduler/pull/111
- https://github.com/unitoio/sync-worker/pull/1406
- https://github.com/unitoio/ucommon/pull/318
- https://github.com/unitoio/webhook-processor/pull/35
- https://github.com/unitoio/webhook-receiver/pull/43
=> 🛠 Post-node10 fix: keep being able to pass specific tests to mocha

package-lock.json, package.json
No release notes on the releases directly but there's only about 15 commits between 3.1.2 and 4.0.0
https://github.com/mike-marcacci/node-redlock/commits/master
their `ioredis` version was bumped from 3.0.0 to 4.10.0
=> 📦 Bump redlock version

package-lock.json, package.json
1. Rename too long `packages:lock:regenerate` script name to `relock`
2. Move confusing `^A.B.C` semver version specifiers to more
intuitive `A.x`. Used regex `"\^(\d+)\.\d+\.\d+"` → `"$1.x"`
3. Fix publishing of test results.
4. Add `audit` to pre-commit.
5. Regenerate pkglock.
=> 🔧 package.json nits

package-lock.json, package.json, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts, test/WriteThroughCache_test.ts
We noticed that most of our connections to a Redis cluster via cachette end up in the primary instance, instead of the replicas.
When reading or writing data to Redis we do use the same Redis connection, which is initialized in the `WriteThroughCache` constructor. 
If this connection is established to a replica and we try to do a write operation through the `WriteThroughCache` class then we will receive a READONLY Error.
if we receive a READONLY error we will keep trying to connect to the cluster until we have a connection with the primary instance (find more details here https://www.npmjs.com/package/ioredis#reconnect-on-error)
```js
this.redisClient = new Redis(redisUrl, {
retryStrategy: () => RedisCache.RETRY_DELAY,
// master failover
reconnectOnError: (err: any) => …
```
=> use different redis connections for write/read operations to avoid landing all operation on the primary instance

src/lib/WriteThroughCache.ts
Fixes `Error while fetching ttl from the Redis cache Error: Stream isn't writeable and enableOfflineQueue options is false`
=> use redisCacheForWriting for getTtl()

.npmrc
This fixes failing to npm install anything with npm 7 (released last week)
in any project that has our `.npmrc`. It currently aborts with error
`UNABLE_TO_GET_ISSUER_CERT_LOCALLY`.
The problem stems from key `ca=`, which is set in all our projects `.npmrc`.
(Doc for `ca` lives at https://docs.npmjs.com/cli/v6/using-npm/config#ca )
It looks like npm 7 changed `.npmrc` parsing; let's run this a few times:
```bash
echo 'npm version:' && npm --version && echo && echo 'contents of .npmrc mentioning "ca":' && cat .npmrc | grep 'ca='; echo && echo 'output of npm config list' && npm config list -l | grep -E 'ca\s+='
```
With ye olden npm **6**, with `ca=` in `.npmrc`, we get (see the two last lines in particular):
```
npm version:
6.14.11
contents of .npmrc mentioning "ca":
ca=
output of npm …
```
=> 🔧 Fix npm install in npm 7

.github/workflows/npm-audit.yml, .github/workflows/npm-lint.yml, .github/workflows/npm-tests.yml
Goal:
The goal is to minimize our credit usage by not running tests on every single commit or on draft pull requests
Docs:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
https://docs.github.com/en/rest/reference/pulls
Forum discussions:
https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/10
=> 💸 Don't run actions on draft pull requests

package-lock.json
CVE-2021-23364 , for dependency `browserslist`
- Version >= 4.0.0 / < 4.16.5
- Upgrade to ~> 4.16.5
=> 🔒 Relock for npm audit fix

src/lib/CacheClient.ts, test/CacheClient_test.ts
When we have a plain object as an argument in a function call that is cached, we are not able to create different keys as cacheKey even if the object is not the same in 2 different calls. This behavior results in fetching the wrong result for a call that has been cached before. 
This PR introduces the support of plain object in `buildCacheKey` function.
We basically get all the values of the plain object and join them with `-` char. In the case of: 
```
getFoo(
arg1 = 'coucou',
arg2 = { nestedProp: 'nestedValue', nestedProp2: 'nestedValue2' },
)
```
Will lead to this cacheKey: `getFoo-coucou-nestedProp-nestedValue-nestedProp2-nestedValue2`.
This PR include the support for `undefined`, `null` and array as well!
=> 💨 Support plain object as key for caching

.github/workflows/npm-audit.yml, .github/workflows/npm-lint.yml, .github/workflows/npm-tests.yml
This PR is part of a propagation to all Unito projects of the GHA trigger
config pimping we validated. This series of PRs generalizes 4 things:
1. It disables running CI jobs on `review_requested`, which makes no sense,
is noise, and uselessly costs GHA credits.
2. It removes leftovers of running CI jobs on `edited` (which happens on
touching PR title / description), also causing noise and GHA credits.
3. It removes all `updated` triggers, which were a noop because a typo here since
day 1 of GHA@unito! This event doesn't exist! It's probably a typo for `edited`,
which we don't want (point 2. above).
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
4. It preserves running cosmetic `pr-name` jobs on `[opened, edited]`,
which is exactly what we …
=> 🔧 Say! No! To! Useless noisy wasteful GHA runs!

src/lib/LocalCache.ts, test/LocalCache_test.ts
While testing locally, I ran into an error in Maestro "Error: not implemented".
This is because we throw when we call `getTtl`. The function has not been implemented yet.
This PR fixes that.
For LocalCache, we use the library `lru-cache`. According to their [docs](https://github.com/isaacs/node-lru-cache#getremainingttlkey), if an item is not cached, `getRemainingTTL` returns 0 and if the item was cached without a TTL, it returns "Infinity". In actually, it returns a very large number with decimals. Therefore, to test if we have a cache that does not expire, we'll look for number > 1799999.
=> 💸 Implement getTtl on LocalCache

.nvmrc, package-lock.json, package.json, src/lib/CacheClient.ts, src/lib/LocalCache.ts, tsconfig.json
- relock
- upgrade node and typescript
- upgrade LRUCache ([breakingchangelog](http://isaacs.github.io/node-lru-cache/#md:breaking-changes-in-version-8))
Redlock 5 still in beta, still not in a hurry to upgrade so leaving as is
=> 🔧 Maintenance/may

package-lock.json, src/lib/CacheClient.ts, src/lib/CacheInstance.ts
Node changed the name of the library from `events` to `node:events` with v16. It still has backward compatibilities it seems, but importing the cachette library failed on one occasion: the result was that the CacheInstance was not resolved as an EventEmitter.
The `package.json` node version is already at `>=18`, so this should be fine.
=> 💨 Use the new way of importing node's EventEmitter

README.md
One was broken, and the others also rely on third-parties that might break too.
They're non essential, and don't add much as already well exposed by GitHub.
Let's remove them.
=> 🔧 README: Remove badges

package.json
Using a postprepare instead of postinstall avoids running the script when installing cachette as a dependency in other projects and runs the script at least as often.
I'm not a fan of git hooks and would love if we didn't need to have this, but I get what you are trying to do, so here's a fix in case we decide we really need this :)
=> 🐛 postprepare instead of postinstall to avoid running when a dependency

src/lib/CacheClient.ts, src/lib/CacheInstance.ts, src/lib/LocalCache.ts, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts, test/RedisCache_test.ts
Exposing Redis' WAIT command which can be useful to ensure data freshness across all nodes of a cluster.
Adding arbitrary default replica of 5 (the maximum supported by AWS Elasticache) and timeout to 200 millisecond. These could be parametrized from the client. Recommending to keep the timeout as low as possible since this is a blocking operation. The client can know whether or not the expected number of replicas acknowledged the last command by comparing the return value of `waitForReplication`. It will return the number of replicas that acknowledge
=> 💨 Expose wait command

.github/workflows/pr-name.yml
Events were incorrect and only firing on PR open, detached from any commit and failing to show up as broken :(
=> 🧰 [patch] GHA: Fix pr-name events

package-lock.json
- Relock'd
Remaining `npm out`: 
- Node: no reason to specify 20.x
- Chai: requires migration to ES Module
- Redlock: still in beta and no reason to update
=> 💡 [patch] Maintenance 2024-03

package-lock.json, package.json, src/lib/RedisCache.ts, src/lib/WriteThroughCache.ts, test/WriteThroughCache_test.ts
This will let users of cachette.WriteThroughCache get basic cache usage hit/miss data.
We need this to measure whether it's reasonable to switch a certain service back to a
regular RedisCache (if volume is fine), or if we actually need a WriteThroughCache.
=> 💨 [minor] WriteThroughCache: Support emitting metrics periodically

src/lib/RedisCache.ts
Deserialization happens on redis values, which are strings. With this PR, I'm simply adjusting the type to better reflect the reality.
=> 💡 [patch] Fix erroneous type

src/lib/WriteThroughCache.ts
Self-explanatory, as reminder/warning of what we learned.
=> 💡 [patch] WriteThroughCache: cautionary JSDoc

.github/workflows/npm-audit.yml, .github/workflows/npm-lint.yml, .github/workflows/npm-tests.yml, .github/workflows/publish-package-on-merge.yml, package-lock.json, package.json
Old actions/cache<v4 is deprecated and will break workflow on Feb 1: https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
And by the way, upgrade similarly ancient actions/xyz we know are safe.
This will be Dependabot-automated someday, but Feb 1 is soon enough that I'll job-de-bras do this now asap.
=> 💡 [patch] GHA: Upgrade actions/cache to v4

.github/workflows/npm-tests.yml, .github/workflows/publish-package-on-merge.yml
We don’t need them during the build, and they can break the build if the GH audit/fund backend is down.
=> 💡 [patch] Build: no npm audit & fund flags in CI

.github/workflows/npm-audit.yml, .github/workflows/npm-lint.yml, .github/workflows/npm-tests.yml, .github/workflows/pr-name.yml, .github/workflows/publish-package-on-merge.yml, .nvmrc, package-lock.json, package.json, tsconfig.json
Repo maintenance:
- Dependencies upgrades/relock
- **BREAKING CHANGE**: major upgrade `lru-cache` 11.x started requiring Node 20, which has been LTS for some time now, so it’s time for cachette to require Node 20 too.
- GHA security fixes with [zizmor](https://github.com/woodruffw/zizmor) audit
=> 💡 [major] Deps upgrades (MAJOR: requires Node 20), gha audit
